name: aptutil
id: aptutil
vibversion: 1.0.0
stages:
- id: build
  base: golang:1.15
  singlelayer: false
  labels:
    maintainer: Vanilla OS Contributors
  args:
    DEBIAN_FRONTEND: noninteractive
    CGO_ENABLED: 0
    GODEBUG: netdns=go
  runs:
    commands:
      - echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/01norecommends
  expose:
    "3142": "tcp"

  modules:
  - name: aptutil
    type: shell
    commands:
      - git clone https://github.com/Vanilla-OS/aptutil.git
      - cd aptutil
      - go install ./...

  - name: ca-certificates
    type: apt
    sources:
      - packages:
        - ca-certificates

  - name: cleanup
    type: shell
    commands:
      - apt autoremove -y
      - apt clean
      - rm -rf /var/cache/*
      - rm -rf /tmp/*
      - rm -rf /var/tmp/*
      - mkdir -p /var/cache/apt/archives/partial

  cmd:
    workdir: /var/lib/aptutil
    exec:
      - /go/bin/go-apt-mirror
